---
postgres_user: 'postgres'

postgres_extra_users:
  - name: 'tech_user'
    password: '{{ tech_user_pass }}'
    privileges:
      - 'CREATEDB'
      - 'CREATEROLE'
      - 'LOGIN'

postgres_extra_databases:
  - name: 'super_db'
    owner: 'tech_user'

postgres_extra_schemas:
  - name: 'super_schema'
    database: 'super_db'
    owner: 'tech_user'

#postgres_extra_schema_privileges:
#  - name: 'test_schema'
#    database: 'test_db'
#    grantee: 'extra_user'
#    privileges:
#      - 'USAGE'
#      - 'CREATE'